<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>Emi-Windows-Dock-Setup</AssemblyName>
    <Product>Emi Liquid Glass Dock</Product>
    <Company>Emiliano</Company>
    <Version>1.0.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>none</DebugType>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <EventSourceSupport>false</EventSourceSupport>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" LogicalName="payload.zip" />
  </ItemGroup>
</Project>
